manga/urls.py
from django.urls import path

from . import views

app_name = "manga"
urlpatterns = [
    path('', views.index, name='index'),
    path('series/<str:id>', views.series, name='series'),
    path('scanlator/', views.scanlators, name='scanlators'),
    path('scanlator/<str:id>', views.scanlator, name='scanlator'),
    path('add_scanlator', views.add_scanlator, name='add_scanlator'),
    path('add_series', views.add_series, name='add_series')
]

mangasite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('manga.urls')),
    path('admin/', admin.site.urls),
]

manga/models.py
from django.db import models


# Create your models here.
class Series(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Scanlator(models.Model):
    name = models.CharField(max_length=255)
    url = models.CharField(max_length=255, blank=True)
    series = models.ManyToManyField(Series, through='ScanlatorSeriesURL', blank=True)

    def __str__(self):
        return self.name


class ScanlatorSeriesURL(models.Model):
    scanlator = models.ForeignKey(Scanlator, on_delete=models.CASCADE)
    series = models.ForeignKey(Series, on_delete=models.CASCADE)
    url = models.CharField(max_length=511)

manga/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django import forms

from manga.models import Series, Scanlator, ScanlatorSeriesURL


class ScanlatorForm(forms.ModelForm):
    class Meta:
        model = Scanlator
        fields = '__all__'


class SeriesForm(forms.ModelForm):
    class Meta:
        model = Series
        fields = '__all__'


class ScanlatorSeriesURLForm(forms.ModelForm):
    class Meta:
        model = ScanlatorSeriesURL
        fields = '__all__'


# Create your views here.
def index(request):
    return render(request, 'manga/index.html', {
        'manga': Series.objects.all()
    })


def scanlators(request):
    return render(request,'manga/scanlators.html', {
        'scanlators': Scanlator.objects.all()
    })


def series(request, id):
    series = Series.objects.get(id=id)

    scanlator_links = ScanlatorSeriesURL.objects.filter(series=id)
    scanlators = {
        scanlator: scanlator_links.get(scanlator=scanlator.id).url
        for scanlator in series.scanlator_set.all()
    }

    return render(request, 'manga/series.html', {
        'series': series,
        'scanlators': scanlators,
    })


def scanlator(request, id):
    scanlator = Scanlator.objects.get(id=id)
    new_scanlator_series_URL = ScanlatorSeriesURL(scanlator=scanlator)

    if request.method == 'POST':
        form = ScanlatorSeriesURLForm(request.POST)

        if form.is_valid():
            # Save ScanlatorSeriesURL
            new_scanlator_series_URL = form.save(commit=False)
            new_scanlator_series_URL.save()
            # Add series to scanlator
            scanlator.series.add(new_scanlator_series_URL.series)
            scanlator.save()

            new_scanlator_series_URL = ScanlatorSeriesURL(scanlator=scanlator)

            return HttpResponseRedirect(reverse('manga:index'))
        else:
            return render(request, 'manga/scanlator.html', {
                'scanlator': scanlator,
                'series': scanlator.series.all(),
                'form': form
            })

    return render(request, 'manga/scanlator.html', {
        'scanlator': scanlator,
        'series': scanlator.series.all(),
        'form': ScanlatorSeriesURLForm(instance=new_scanlator_series_URL)
    })


def add_scanlator(request):
    if request.method == 'POST':
        form = ScanlatorForm(request.POST)

        if form.is_valid():
            new_scanlator = form.save(commit=False)
            new_scanlator.save()

            return HttpResponseRedirect(reverse('manga:index'))
        else:
            # Re-render with existing information
            return render(request, 'manga/add_scanlator.html', {
                'form': form
            })

    return render(request, 'manga/add_scanlator.html', {
        'form': ScanlatorForm()
    })


def add_series(request):
    if request.method == 'POST':
        form = SeriesForm(request.POST)

        if form.is_valid():
            new_series = form.save(commit=False)
            new_series.save()

            return HttpResponseRedirect(reverse('manga:index'))
        else:
            # Re-render with existing information
            return render(request, 'manga/add_series.html', {
                'form': form
            })

    return render(request, 'manga/add_series.html', {
        'form': SeriesForm()
    })

manga/templates/manga/add_scanlator.html
{% extends "manga/layout.html" %}

{% block body %}
<h1>New Scanlator</h1>

<form action="{% url 'manga:add_scanlator' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
{% endblock %}

manga/templates/manga/add_series.html
{% extends "manga/layout.html" %}

{% block body %}
<h1>New Series</h1>

<form action="{% url 'manga:add_series' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
{% endblock %}

manga/templates/manga/index.html
{% extends "manga/layout.html" %}

{% block body %}
<h1>All manga</h1>

<ul>
    {% for m in manga %}
    <li><a href="series/{{ m.id }}">{{ m.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

manga/templates/manga/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<a href="{% url 'manga:index' %}">Home</a>
<a href="{% url 'manga:scanlators' %}">Scanlators</a>
<a href="{% url 'manga:add_scanlator' %}">Add Scanlator</a>
<a href="{% url 'manga:add_series' %}">Add Series</a>

{% block body %}
{% endblock %}

</body>
</html>

manga/templates/manga/scanlator.html
{% extends "manga/layout.html" %}

{% block body %}
<h1>{{ scanlator.name }}</h1>

<ul>
    {% for s in series %}
    <li><a href="/series/{{ s.id }}">{{ s.title }}</a></li>
    {% endfor %}
</ul>

<form action="/scanlator/{{ scanlator.id }}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
{% endblock %}

manga/templates/manga/scanlators.html
{% extends "manga/layout.html" %}

{% block body %}
<h1>All scanlators</h1>

<ul>
    {% for scanlator in scanlators %}
    <li><a href="/scanlator/{{ scanlator.id }}">{{ scanlator.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

manga/templates/manga/series.html
{% extends "manga/layout.html" %}

{% block body %}
<h1>{{ series.title }}</h1>

<ul>
    {% for scanlator, url in scanlators.items %}
    <li>
        <a href={{ url }}>{{ scanlator.name }}</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}